#!/bin/bash

echo "========================================="
echo "Logo Replacement Guide"
echo "========================================="
echo ""
echo "Three ways to add your logo:"
echo ""
echo "1. UPLOAD YOUR LOGO FILE:"
echo "   Copy your logo to: /app/frontend/public/logo.png"
echo "   Command: cp /path/to/your/logo.png /app/frontend/public/logo.png"
echo ""
echo "2. USE EXTERNAL URL:"
echo "   Edit /app/frontend/src/pages/LoginPage.js"
echo "   Change: src=\"/logo.png\""
echo "   To: src=\"https://your-site.com/your-logo.png\""
echo ""
echo "3. CHANGE RESTAURANT NAME:"
echo "   The app currently shows 'BistroFlow'"
echo "   Edit /app/frontend/src/pages/LoginPage.js"
echo "   Replace 'BistroFlow' with your restaurant name"
echo ""
echo "========================================="
echo "Current logo locations in the app:"
echo "========================================="
echo "- Login page: /app/frontend/src/pages/LoginPage.js (line 32)"
echo "- Receipt prints: Search for 'BistroFlow' in:"
echo "  * /app/frontend/src/pages/ReceptionDashboard.js"
echo ""
echo "After making changes, the app will auto-reload!"
echo "========================================="
